name: biomedparse
channels:
  - pytorch
  - defaults
dependencies:
  - python=3.11
  - pip
  - pip:
    - -r assets/requirements/requirements.txt
    - git+https://github.com/MaureenZOU/detectron2-xyz.git
