name: grandqc
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - openslide
  - openslide-python
  - pip
  - pip:
    - numpy
    - Pillow
    - matplotlib
    - torch
    - torchvision
    - opencv-python
    - scikit-image
    - tqdm
    - pandas
    - scipy
    - tiffslide

variables:
  PYTHONPATH: $PYTHONPATH:$CONDA_PREFIX/lib/python3.10/site-packages 